version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: web-game-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/web-game
      - JWT_SECRET=your_jwt_secret_key_here
      - CORS_ORIGIN=http://20.184.37.11
    depends_on:
      - mongo
    networks:
      - web-game-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        # 替换为您的VPS IP或域名
        - REACT_APP_API_URL=/api
    container_name: web-game-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - web-game-network

  mongo:
    image: mongo:latest
    container_name: web-game-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - web-game-network

networks:
  web-game-network:
    driver: bridge

volumes:
  mongo-data:
